#!/usr/bin/env ruby

def validate_csv_file!(csv_file)
  return if csv_file && File.exist?(csv_file)
  usage
  $stderr.puts 'Please provide a metadata file to import.'
  exit(1)
end

def validate_output_path!(output_path)
  return if output_path
  $stderr.puts 'Files directory was left blank. No files will be ingested'
end

def load_app
  # puts 'Loading configs...'
  # require File.expand_path('../../config/environment', __FILE__)
  require 'fedora_downloader'
  puts 'Starting import...'
end

def main(csv_file, output_path)
  validate_csv_file!(csv_file)
  validate_output_path!(output_path)
  load_app

  size = FedoraDownloader::BookDownloader.new(csv_file, output_path).process

  puts "Downloaded #{size} books."
end

def usage
  $stderr.puts "Usage: #{$PROGRAM_NAME} <csv file> <files directory>"
end

main(ARGV[0], ARGV[1])
